<div>
    <h1>Hello</h1>
    <?php
    $path = Mage::getBaseUrl('media') . 'catalog/product';
    //var_dump($products = $this->getProducts());exit;
    $products = $this->getProducts();
    foreach ($products as $product) {

        echo "<a href='" . Mage::getBaseUrl() . $product->getUrlPath() . "'>" . $product->getName() . "</a>";
        echo "<a href='" . Mage::getBaseUrl() . $product->getUrlPath() . "'>" . 
             "<img src='" . $path . $product->getImage() . "' width='100px'></a>";
        echo $this->getPriceHtml($product);
        echo $product->getShortDescription();
        echo '<br><br>';
    }
    ?>
</div>